name: Games_Core
main: Core\Main
api: 4.0.0
version: 3.0.0
author: VectorNetworkDevelopmentTeam
authors:
  - InkoHX
  - MazaiCrafty
  - yuko fuyutsuki
  - DusKong
permissions:
  vnp.command.ping:
    permission: true
  vnp.command.status:
    permission: true
  vnp.command.rankshop:
    permission: true
  vnp.command.setmoney:
    permission: op
  vnp.command.settag:
    permission: op
  vnp.command.selectgame:
    permission: true
  vnp.command.debug:
    permission: op
  vnp.command.killsound:
    permission: true
  vnp.command.addtag:
    permission: op
  vnp.command.gamestatus:
    permission: true
  vector.network.player:
    permission: true
  vector.network.admin:
    permission: op