name: Games_Core
main: Core\Main
api: 4.0.0
version: 3.0.0
author: VectorNetworkDevelopmentTeam
authors:
- InkoHX
- MazaiCrafty
- yuko fuyutsuki
- DusKong
permissions:
  vnp.command.ping:
    default: true
  vnp.command.stats:
    default: true
  vnp.command.rankshop:
    default: true
  vnp.command.setmoney:
    default: op
  vnp.command.settag:
    default: op
  vnp.command.selectgame:
    default: true
  vnp.command.debug:
    default: op
  vnp.command.killsound:
    default: true
  vnp.command.addtag:
    default: op
  vnp.command.gamestatus:
    default: true
  vector.network.player:
    default: true
  vector.network.admin:
    default: op